-- Schedule Data Export
-- Generated for Replit sync

DELETE FROM weekly_schedule_classes;
DELETE FROM alternating_weeks_config;

-- Insert Classes
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('01', 'saturday', '08:00', '09:30', 'Analysis1', 'Amphi H', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('01', 'saturday', '09:40', '11:10', 'Algebra1', 'Amphi H', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('01', 'saturday', '11:20', '12:50', 'Statistics1', 'Room 395T', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('01', 'saturday', '13:00', '14:30', 'Algorithm1', 'Room C206', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('01', 'saturday', '14:40', '16:10', 'Analysis1', 'Room C206', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('01', 'sunday', '08:00', '09:30', 'Algorithm1', 'Amphi O', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('01', 'sunday', '09:40', '11:10', 'Analysis1', 'Room 301D', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('01', 'sunday', '14:40', '16:10', 'Analysis1', 'Amphi K', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('01', 'monday', '08:00', '09:30', 'Algorithm1', 'LabE2.01', 'Laboratory Session', 1, 'algorithm1');
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('01', 'monday', '11:20', '12:50', 'ICT', 'Online (Google Meet)', 'Online Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('01', 'tuesday', '11:20', '12:50', 'Statistics1', 'Room C5', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('01', 'tuesday', '13:00', '14:30', 'Algebra1', 'Room 320D', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('01', 'tuesday', '14:40', '16:10', 'Algebra1', 'Amphi M', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('01', 'wednesday', '09:00', '10:30', 'English1', 'Online (Google Meet)', 'Online Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('01', 'thursday', '08:00', '11:10', 'Statistics1', 'LabE2.01', 'Laboratory Session', 1, 'statistics1');
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('02', 'saturday', '08:00', '09:30', 'Analysis1', 'Amphi H', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('02', 'saturday', '09:40', '11:10', 'Algebra1', 'Amphi H', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('02', 'saturday', '11:20', '12:50', 'Statistics1', 'Room 395T', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('02', 'saturday', '13:00', '14:30', 'Analysis1', 'Room 320D', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('02', 'saturday', '14:40', '16:10', 'Algorithm1', 'Room 336D', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('02', 'sunday', '08:00', '09:30', 'Algorithm1', 'Amphi O', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('02', 'sunday', '11:20', '12:50', 'Analysis1', 'Room 332D', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('02', 'sunday', '14:40', '16:10', 'Analysis1', 'Amphi K', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('02', 'monday', '08:00', '09:30', 'Algorithm1', 'Lab E0.05', 'Laboratory Session', 1, 'algorithm1');
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('02', 'monday', '11:20', '12:50', 'ICT', 'Online (Google Meet)', 'Online Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('02', 'tuesday', '11:20', '12:50', 'Algorithm1', 'Room C6', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('02', 'tuesday', '13:00', '14:30', 'Statistics1', 'Room 362', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('02', 'tuesday', '14:40', '16:10', 'Algebra1', 'Amphi M', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('02', 'wednesday', '09:00', '10:30', 'English1', 'Online (Google Meet)', 'Online Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('02', 'thursday', '08:00', '11:10', 'Statistics1', 'Lab E2.01', 'Laboratory Session', 1, 'statistics1');
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('03', 'saturday', '08:00', '09:30', 'Analysis1', 'Amphi H', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('03', 'saturday', '09:40', '11:10', 'Algebra1', 'Amphi H', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('03', 'saturday', '11:20', '12:50', 'Statistics1', 'Room 395T', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('03', 'saturday', '13:00', '14:30', 'Analysis1', 'Room 320D', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('03', 'saturday', '14:40', '16:10', 'Statistics1', 'Room 304', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('03', 'sunday', '08:00', '09:30', 'Algorithm1', 'Amphi O', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('03', 'sunday', '11:20', '12:50', 'Analysis1', 'Room 332D', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('03', 'sunday', '13:00', '14:30', 'Algebra1', 'Room R3', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('03', 'sunday', '14:40', '16:10', 'Analysis1', 'Amphi K', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('03', 'monday', '09:40', '11:10', 'Algorithm1', 'Lab E2.07', 'Laboratory Session', 1, 'algorithm1');
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('03', 'monday', '11:20', '12:50', 'ICT', 'Online (Google Meet)', 'Online Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('03', 'tuesday', '11:20', '12:50', 'Algorithm1', 'Room 385', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('03', 'tuesday', '14:40', '16:10', 'Algebra1', 'Amphi M', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('03', 'wednesday', '09:00', '10:30', 'English1', 'Online (Google Meet)', 'Online Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('03', 'thursday', '08:00', '11:10', 'Statistics1', 'Lab E0.05', 'Laboratory Session', 1, 'statistics1');
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('04', 'saturday', '08:00', '09:30', 'Analysis1', 'Amphi H', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('04', 'saturday', '09:40', '11:10', 'Algebra1', 'Amphi H', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('04', 'saturday', '11:20', '12:50', 'Statistics1', 'Room 395T', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('04', 'saturday', '13:00', '14:30', 'Statistics1', 'Room 300', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('04', 'saturday', '14:40', '16:10', 'Analysis1', 'Room C206', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('04', 'sunday', '08:00', '09:30', 'Algorithm1', 'Amphi O', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('04', 'sunday', '09:40', '11:10', 'Analysis1', 'Room 301D', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('04', 'sunday', '11:20', '12:50', 'Algebra1', 'Room R3', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('04', 'sunday', '14:40', '16:10', 'Analysis1', 'Amphi K', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('04', 'monday', '09:40', '11:10', 'Algorithm1', 'Lab E0.05', 'Laboratory Session', 1, 'algorithm1');
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('04', 'monday', '11:20', '12:50', 'ICT', 'Online (Google Meet)', 'Online Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('04', 'tuesday', '13:00', '14:30', 'Algorithm1', 'Room R6', 'Tutorial Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('04', 'tuesday', '14:40', '16:10', 'Algebra1', 'Amphi M', 'Course', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('04', 'wednesday', '09:00', '10:30', 'English1', 'Online (Google Meet)', 'Online Session', 0, NULL);
INSERT INTO weekly_schedule_classes (group_number, day_name, time_start, time_end, course, location, class_type, is_alternating, alternating_key) VALUES ('04', 'thursday', '08:00', '11:10', 'Statistics1', 'Lab E0.05', 'Laboratory Session', 1, 'statistics1');

-- Insert Alternating Week Configuration
INSERT INTO alternating_weeks_config (alternating_key, reference_date, description) VALUES ('algorithm1', '2025-11-15', 'Laboratory Session Algorithm1 (Monday)');
INSERT INTO alternating_weeks_config (alternating_key, reference_date, description) VALUES ('statistics1', '2025-11-15', 'Laboratory Session Statistics1 (Thursday)');
